<p>This file can be generated and saved only in configured environment with executable "phantomjs" binary.</p>
<p>Please configure it in your environment.</p>
<p>The file is generated by a script which located in <? echo $this->get_widget_directory(); ?>/phantom/print.js</p>
